---
title: "About"
---

## Background
My name is Jack Liu, and I am a 2024 UBC graduate with a Bachelor of Science in Sustainable Agriculture. Originally from Fredericton, New Brunsick, I moved to Vancouver at 18 to come to UBC.
Prior to coming to the UBC MDS program, I have been working for a year and half at Sungiven Foods (White Rock) as a Store Receiver.

## Why Data Science
I became interested in Data Science toward the end of my bachelor’s degree. I have always enjoyed working with numbers, analyzing problems, and finding solutions that support better decision-making.
During my work as a Receiver, I gained experience with data entry, inventory tracking, and records management. However, this made me realize that I wanted to do more than simply manage data, and I wanted to use data to analyze problems and support decision-making.
Thus, I enrolled in the UBC MDS program, where I hope to develop the technical skills needed for a career in data analysis. The accelerated 10-month format also fits well with my goal of transitioning into the field quickly.

## Outside of Data Science
I am an avid fan of football, especially the English Premier League. My favorite team is Chelsea FC. I am also a huge foodie, and I enjoy exploring various restaurants in Vancouver with diverse cuisines. My favorite food is Donair.
